runtime: python
env: flex 
DEBUG: 'False'

env_variables:
  DB_HOST: '34.72.251.111'
  DB_PORT: '5432'
  DB_NAME: 'postgres'
  DB_USER: 'user2' 
  DB_PASSWORD: 'password'

beta_settings:
  cloud_sql_instances: ground-up-app:us-central1:psql-serv